### ISSUE TITLE
0.1.0 upgrade path?

### ISSUE THREAD

**Issue by mathieumg** [Cellule/npm-lifecycle-runner#2]
I updated from `0.0.5` to `0.1.0` and stuff broke and I'm trying to figure out why. There are no release notes or version tags so it's proving harder than I thought. :P

I would have liked to seize the opportunity and leverage the CLI changes in https://github.com/Cellule/npm-lifecycle-runner/commit/ee785e4043bc61843a672963a4e51ba5a1c4fcee but I'm not even sure what the proper approach is. Regardless, I've ran into more general CLI issues which I've reported in https://github.com/Cellule/npm-lifecycle-runner/issues/1

Perhaps these CLI issues are related to my current problem, however. When I `npm install` a module that has as a dependency a module in which I use `npm-lifecycle-runner` for the `install` event, I get the following error:

```
 error - npm-lifecycle-runner@0.1.0 install: `node cli "eslint-myrules cp"`
         Exit status 8
 error - Failed at the npm-lifecycle-runner@0.1.0 install script 'node cli "eslint-myrules cp"'.
         This is most likely a problem with the npm-lifecycle-runner package,
         not with npm itself.
```

With the very same code/configuration that worked properly under `0.0.5`.

**Edit:** Just tested under `0.0.6` and it works properly. I simply couldn't install `0.0.7`, I got more CLI errors on installation. If this is a generalized issue, `0.0.7` should be unpublished from npm.

**Comment by Cellule** [comment]
I'm curious to see what are the errors when you upgrade from `0.0.5` to any other version. Technically they should all be compatible. I pushed to `0.1.0` to give me more flexibility in the versioning and because I added a feature (the cli which is not documented I admit).

**Comment by mathieumg** [comment]
For `0.0.7`:

```
> npm-lifecycle-runner@0.0.7 install /home/mathieu/Git/auctionex/modules.communications/node_modules/npm-lifecycle-runner
> node installScript.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/home/mathieu/Git/auctionex/modules.communications/node_modules/npm-lifecycle-runner/installScript.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
 error - Linux 3.5.0-18-generic
 error - argv "node" "/home/mathieu/local/bin/yapm" "i" "npm-lifecycle-runner@0.0.7"
 error - node v0.10.29
 error - npm  v2.4.2
 error - code ELIFECYCLE

 error - npm-lifecycle-runner@0.0.7 install: `node installScript.js`
         Exit status 8
 error - Failed at the npm-lifecycle-runner@0.0.7 install script 'node installScript.js'.
         This is most likely a problem with the npm-lifecycle-runner package,
         not with npm itself.
         Tell the author that this fails on your system:
             node installScript.js
         You can get their info via:
             npm owner ls npm-lifecycle-runner
         There is likely additional logging output above.
```

For 0.1.0 this is the error I showed in the OP, when installing a module that has `npm-lifecycle-runner` as a dependency.

**Comment by Cellule** [comment]
The version 0.0.7 was indeed broken, I removed it from npm.
for 0.1.0, I am starting to believe the problem might be related to when npm actually runs the install script.
I will leave this open to remind me to add some documentation once the issues are resolved.
We shall continue the discussion on #1 instead for fixes
